### PR TITLE
[#103] Setup mutation coverage

### PR DESCRIPTION
**Pull request by mthmulders**
This sets up mutation coverage using PIT. I've made a guess as to which modules would be most relevant to assess.

If you like to have a nice badge for the README, I can help you with that, too. Just let me know.

### CODE REVIEW

**Comment by bmarwell** [comment]
Nice! Is this ready to merge already? 😃

**Comment by mthmulders** [comment]
> Nice! Is this ready to merge already? 😃

If you're happy with only having a report when you run it locally (on your machine): yes.

If you want a report that you can browse from anywhere and/or a badge in README: no.

You decide :-)

**Comment by bmarwell** [comment]
I like it, I think it is a good addition! 👍🏻 
I would love to see an example repository with a badge. ;-)

**Comment by mthmulders** [comment]
> I would love to see an example repository with a badge. ;-)

How about [PUML Maven Plugin](https://github.com/mthmulders/puml-maven-plugin) or [Stryker Dashboard reporter for PIT](https://github.com/mthmulders/pit-stryker-dashboard-reporter)? Both have a badge for _Mutation score_; if you click it, you'll see an online report with the mutation testing results.

**Pull request merged**
